{{- if .Values.csi.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jellyfin-cache.fullname" . }}-csi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jellyfin-cache.labels" . | nindent 4 }}
{{- end }}
