{{- if and (not .Values.rclone.existingSecret) .Values.rclone.configContent }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-rclone" (include "jellyfin-cache.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jellyfin-cache.labels" . | nindent 4 }}
type: Opaque
stringData:
  rclone.conf: |
    {{- .Values.rclone.configContent | nindent 4 }}
{{- end }}
