apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin-cache.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jellyfin-cache.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jellyfin-cache.selectorLabels" . | nindent 4 }}
  ports:
    {{- if eq .Values.mount.type "9p" }}
    - name: p9
      port: {{ .Values.mount.p9Listen | splitList ":" | last }}
      targetPort: p9
      protocol: TCP
    {{- else }}
    - name: nfs
      port: 2049
      targetPort: nfs
      protocol: TCP
    {{- end }}
    {{- if .Values.webhook.enabled }}
    - name: webhook
      port: 8089
      targetPort: webhook
      protocol: TCP
    {{- end }}
    {{- if .Values.api.enabled }}
    - name: api
      port: 8090
      targetPort: api
      protocol: TCP
    {{- end }}
